local section_gap = require("helpers.section_gap")

require("items.apple")
section_gap.add("section.gap.left1", "left")
require("items.mode")
require("items.spaces")
section_gap.add("section.gap.left2", "left")
require("items.tmux")
require("items.date")
require("items.battery")
require("items.volume")
require("items.input")
section_gap.add("section.gap.right", "right")
require("items.network")
require("items.memory")
require("items.cpu")
require("items.right")
