[[snippets]]
name = "git"
trigger = "g"
snippet = "git"

# log
[[snippets]]
name = "git log"
trigger = "gl"
snippet = 'git log --pretty=format:"%C(auto)%h (%C(blue)%cd%C(auto))%d %s %Cblue" --date=format:"%Y/%m/%d %H:%M:%S" -n 10'

[[snippets]]
name = "git log --graph"
trigger = "ggr"
snippet = "git log --graph --date=short --decorate=short --pretty=format:'%Cgreen%h %Creset%cd %Cblue%cn %Cred%d %Creset%s'"

[[snippets]]
name = "git reflog"
trigger = "grl"
snippet = "git reflog"

# branch
[[snippets]]
name = "git branch --all"
trigger = "gb"
snippet = "git branch --all"

[[snippets]]
name = "git branch -D"
trigger = "gbD"
snippet = "git branch -D"

[[snippets]]
name = "branch name"
trigger = "B"
snippet = "$(git symbolic-ref --short HEAD)"
evaluate = true
global = true
context = '^git\s'

# status
[[snippets]]
name = "git status"
trigger = "gs"
snippet = "git status"

[[snippets]]
name = "(git status) -uno"
trigger = "u"
snippet = "-uno"
global = true
context = '^git\sstatus\s'

# diff
[[snippets]]
name = "git diff"
trigger = "gd"
snippet = "git diff"

[[snippets]]
name = "(git diff) --word-diff"
trigger = "w"
snippet = "--word-diff"
global = true
context = '^git\sdiff\s'

[[snippets]]
name = "(git diff) --name-only"
trigger = "n"
snippet = "--name-only"
global = true
context = '^git\sdiff\s'

# add
[[snippets]]
name = "git add"
trigger = "ga"
snippet = "git add"

[[snippets]]
name = "git add ."
trigger = "gaa"
snippet = "git add ."

# commit
[[snippets]]
name = "git commit"
trigger = "gc"
snippet = "git commit"

[[snippets]]
name = "git commit -m"
trigger = "gcm"
snippet = 'git commit -m "{}"'

[[snippets]]
name = "(git) commit -m"
trigger = "cm"
snippet = 'commit -m "{}"'
global = true
context = '^git\s'

[[snippets]]
name = "git commit --allow-empty -m \"(branch-name)\""
trigger = "gcae"
snippet = 'git commit --allow-empty -m "(branch-name)"'

[[snippets]]
name = "(git commit) --allow-empty"
trigger = "ae"
snippet = "--allow-empty"
global = true
context = 'git\scommit\s'

[[snippets]]
name = "git start working on current branch"
trigger = "gcfc"
snippet = 'git commit --allow-empty -m "start working on $(git rev-parse --abbrev-ref HEAD)"'

# reset
[[snippets]]
name = "git reset"
trigger = "gr"
snippet = "git reset"

[[snippets]]
name = "(git reset) --soft"
trigger = "s"
snippet = "--soft"
global = true
context = '^git\sreset\s'

[[snippets]]
name = "(git reset) --hard"
trigger = "h"
snippet = "--hard"
global = true
context = '^git\sreset\s'

[[snippets]]
name = "(git reset) HEAD^"
trigger = "H"
snippet = "HEAD^"
global = true
context = '^git\sreset\s'

# checkout
[[snippets]]
name = "git checkout"
trigger = "gco"
snippet = 'git checkout "{}"'

[[snippets]]
name = "git checkout -b"
trigger = "gcob"
snippet = 'git checkout -b "{}" && git commit --allow-empty -m "start working on $(git rev-parse --abbrev-ref HEAD)"'

[[snippets]]
name = "git checkout develop"
trigger = "gcod"
snippet = "git checkout develop"

# fetch
[[snippets]]
name = "git fetch"
trigger = "gf"
snippet = "git fetch"

# merge
[[snippets]]
name = "git merge"
trigger = "gm"
snippet = "git merge origin/{} # 基本的にremote branchからとる主義"

# pull
[[snippets]]
name = "git pull"
trigger = "gp"
snippet = "git pull"

# push
[[snippets]]
name = "git push"
trigger = "gP"
snippet = "git push"

[[snippets]]
name = "git push origin HEAD"
trigger = "gPoh"
snippet = "git push origin HEAD"

[[snippets]]
name = "(git push) origin HEAD"
trigger = "oh"
snippet = "origin HEAD"
global = true
context = '^git\spush\s'

[[snippets]]
name = "(git push) --force-with-lease"
trigger = "f"
snippet = "--force-with-lease"
global = true
context = '^git\spush\s'

# その他の git コマンド
[[snippets]]
name = "git clone"
trigger = "gcl"
snippet = "git clone"

[[snippets]]
name = "git cherry-pick"
trigger = "gcp"
snippet = "git cherry-pick"

# マージされたローカルブランチを削除するコマンド
[[snippets]]
name = "delete merged branches"
trigger = "git-db"
snippet = "git pull && git fetch --tags --prune && git branch --merged=$(git bn) | grep -vE 'develop|master|main|$(git bn)' | xargs git branch -d"

# ローカルブランチのgrep
[[snippets]]
name = "grep local branch"
trigger = "gbls"
snippet = 'git branch -a | grep "{}"'
