[[snippets]]
name = "terraform"
trigger = "te"
snippet = "terraform"

[[snippets]]
name = "terraform init"
trigger = "tei"
snippet = "terraform init"

[[snippets]]
name = "terraform validate"
trigger = "tev"
snippet = "terraform validate"

[[snippets]]
name = "(tenv) install terrform"
trigger = "i"
snippet = "tf install"
global = true
context = '^tenv\s'
