customCommands:
  - key: "H"
    context: "commits"
    command: "hunk show {{.SelectedCommit.Hash}}"
    output: terminal
  - key: "H"
    context: "files"
    command: "hunk diff"
    output: terminal
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
gui:
  language: ja
  nerdFontsVersion: "3"
  showIcons: true
  sidePanelWidth: 0.15
  theme:
    selectedLineBgColor:
      - underline
os:
  editPreset: nvim-remote
refresher:
  refreshInterval: 3
