name: Nix Build (linux)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "flake.lock"
      - "**/*.nix"
      - ".github/workflows/nix-build-linux.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-build-linux-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-build-linux-${{ runner.os }}-
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-build-linux-${{ runner.os }}-
          purge-last-accessed: P7D
          purge-primary-key: never

      - name: Build Linux home-manager configuration
        run: nix build .#homeConfigurations.ci@linux.activationPackage --print-build-logs
