name: Nix Build (linux)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "flake.lock"
      - "**/*.nix"
      - ".github/workflows/nix-build-linux.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Build Linux home-manager configuration
        run: nix build .#homeConfigurations.ci@linux.activationPackage --print-build-logs
