name: Update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.AUTOMATION_CLIENT_ID }}
          private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ steps.app-token.outputs.token }}

      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-last-accessed: P7D
          purge-primary-key: never

      - uses: DeterminateSystems/update-flake-lock@v28
        with:
          token: ${{ steps.app-token.outputs.token }}
          pr-title: "chore(nix): update flake.lock"
          pr-labels: dependencies
          pr-body: |
            Automated weekly update of flake.lock.

            ### Updated inputs
            {{ env.GIT_COMMIT_MESSAGE }}
